### ISSUE TITLE
Next Button Conditional logic doesn't work.

### ISSUE THREAD

**Issue by orest22** [tyxla/Gravity-Forms-Multiple-Form-Instances#17]
Hello! 
I really like your plugin, it's very handy.
Could you check if it's bug or mb it's only some problem in my form.
I have  conditional logic on next page button but the button is visible every time. I've try to turn of your plugin and it start working.

Thanks!

**Comment by tyxla** [comment]
Hi @orest22,

Thanks for reporting! I'll investigate the issue later today and will get back to you. 

Regards,
Marin

**Comment by tyxla** [comment]
Hi @orest22,

The issue has been fixed. You can see it here: https://github.com/tyxla/Gravity-Forms-Multiple-Form-Instances/commit/a5a0d32c1c6ae07a3fc019b7d5af7e77fc818f31.

A new plugin version will be released the next few hours, stay tuned.

Thank you for reporting the issue!

Regards,
Marin

**Comment by orest22** [comment]
Thank you as well! I'm appreciated!

**Comment by tyxla** [comment]
Glad I was able to help :) 

If you need the fixed version and can't wait another hour, feel free to pull it from here.

And good luck with your project ;)

**Comment by tyxla** [comment]
Hey @orest22,

A new minor version has just been released. Feel free to update to receive the fix.

Cheers,
Marin

**Comment by msdrama011983** [comment]
Hello,
I have the same problem.  The conditional logic next button does not work for page sections.
