### ISSUE TITLE
Support for loading scripts in the footer

### ISSUE THREAD

**Issue by CFXd** [tyxla/Gravity-Forms-Multiple-Form-Instances#4]
Is there a way we can get multiple instances to obey the [`gform_init_scripts_footer` filter](http://www.gravityhelp.com/documentation/page/Gform_init_scripts_footer)? I'm loading jQuery in the footer of a project and I've deferred the Gravity Forms scripts to load in the footer as well, but it appears that one of my duplicate form instances is not obeying which leads to console errors and most likely submission issues.

**Comment by tyxla** [comment]
That is not directly related with the plugin itself, however the reason for it should be quite easy to resolve. 

Can you please provide me with additional details? What exactly seems to be the issue? Perhaps the scripts are displayed twice, or they are being displayed in the header? Also, what exactly are the errors in the console? I'd need a little more information in order to help you.

**Comment by CFXd** [comment]
Sure thing, apologies for not including that stuff from the start!

Without that filter and with jQuery loaded in the footer, Chrome throws an identical console error for each form present on the page:
```
Uncaught ReferenceError: jQuery is not defined
```
The line number reference is the opening `<script>` tag that is output after each form immediately after the blank `<iframe>`.

When I move jQuery into the `<head>` everything works just fine, but I prefer to keep it in the footer.

So when I have jQuery in the footer, I use the `gform_init_scripts_footer` filter. On a site without the multiple instances plugin, it works just fine. But when I add the multiple instances plugin I get the same error with the same line reference.

The scripts do not appear to display twice.

I hope this is enough to go on, if not then let me know and I can setup a staging server where you can view this issue.

Thanks!

**Comment by CFXd** [comment]
Hang on, I am using a beta version of GF and it may be a GF issue. Pause for now, will update this issue when I figure out where the error may be coming from.
