### ISSUE TITLE
Plugin incompatible Gravity Forms 2.5

### ISSUE THREAD

**Issue by badfeather** [tyxla/Gravity-Forms-Multiple-Form-Instances#40]
It looks like the random form id is no longer being passed to the 'gform_post_render' hooks, and they're instead using the actual form ID. This has caused all of my forms embedded using the `gravity_form()` template tag to never load, because the inline `display: none;` style never gets cleared on form load.

**Comment by badfeather** [comment]
I've done more digging on this issue. I believe it was related to a theme implementation. Closing.

**Comment by lkraav** [comment]
We're seeing the exact same thing, though. What potential implementation problems did you see @badfeather

**Comment by badfeather** [comment]
In my case, I was attempting to use multiple non-ajax forms. When I switched them to the ajax implementation, the plugin worked as expected.
